
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
security.jwt.secret=ZmFrZVNlY3JldEtleUZvckpXVC1QbGFjZUhvbGRlci0xMjM0NTY=
security.jwt.expiration-ms=3600000
spring.application.name=backendpfe

# Gemini API key is read from environment variable GEMINI_API_KEY (do NOT commit keys here)
# Alternatively you can set it here (NOT RECOMMENDED FOR PUBLIC REPOS). Remove leading # to use.
gemini.api.key=AIzaSyCTnjYSWGIQ4_GkVXR8cXOCnzuBEdlj36M

# Google OAuth Web Client ID used for server-side ID token verification
google.client.id=426439195249-e7ip3iqoiu42b8g53gnbrda3nffdv6cf.apps.googleusercontent.com

# Email configuration (example using Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abdellahaissan7@gmail.com
spring.mail.password=adsuttcxtlwsmabh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
app.mail.from=abdellahaissan7@gmail.com
